name: issues

on:
  issues:
    types: [opened, edited]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Slack message on build start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C07GCKW8VNH
          payload: |
            {
             "actions": [
                {
                  "type": "button",
                  "text": "Ver Issue",
                  "url": "${{ github.event.issue.html_url }}"
                }
              ] ,
              "channel": "C07GCKW8VNH",
              "text": "📢 Atención: Nueva incidencia reportada",
              "attachments": [
                {
                  "color": "#FFA500",
                  "text": "Detalles del *Issue*:\n*Título:* ${{ github.event.issue.title }}\n*Autor:* ${{ github.event.sender.login }}\n*Body:* ${{ github.event.issue.body }}\n*Issue URL:* ${{ github.event.issue.html_url }}\n*Number:* ${{ github.event.issue.number }}"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  
