name: issues

on:
  issues:
    types: [opened, edited]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Slack message on build start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C07GCKW8VNH
          payload: |
            {
              "channel": "C07GCKW8VNH",
              "text": "游닉 Atenci칩n: Nueva incidencia reportada",
              "attachments": [
                {
                  "color": "#FFA500",
                  "text": "Detalles del *Pull Request*:\n*T칤tulo:* ${{ github.event.issue.title }}\n*Autor:* ${{ github.event.sender.login }}\n*Body:* ${{ github.event.issue.body }}\n*Issue URL:* ${{ github.event.issue.html_url }}\n*Number:* ${{ github.event.issue.number }}"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Slack message with build result
        if: success() || failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C07G7NCBVQW
          payload: |
            {
              "channel": "C07G7NCBVQW",
              "text": "游닉 Resultado de la construcci칩n.",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#36a64f' || job.status == 'failure' && '#ff0000' || '#FFA500' }}",
                  "text": "Estado del trabajo: ${{ job.status }}\nEnlace a los logs: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
