name: Simple PR Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo PR URL
        run: echo "PR opened: ${{ github.event.pull_request.html_url }}"
