name: Notify on Push to UAT

on:
  push:
    branches:
      - UAT

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Slack Notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMITTER_NAME=$(git log -1 --pretty='%cn')
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          PAYLOAD=$(cat <<EOF
          {
            "channel": "C07GJ2TGW7N",
            "text": "🚀 Se han añadido nuevos cambios a la rama UAT",
            "attachments": [
              {
                "color": "#36a64f",
                "pretext": "Detalles del último commit:",
                "fields": [
                  {
                    "title": "Mensaje del Commit",
                    "value": "${COMMIT_MESSAGE}",
                    "short": false
                  },
                  {
                    "title": "Autor",
                    "value": "${COMMITTER_NAME}",
                    "short": true
                  }
                ],
                "actions": [
                  {
                    "type": "button",
                    "text": "Ver Commit",
                    "url": "${COMMIT_URL}",
                    "style": "primary"
                  }
                ],
                "footer": "GitHub Actions",
                "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                "ts": "${{ github.event.head_commit.timestamp }}"
              }
            ]
          }
          EOF
          )
          curl -X POST -H 'Content-type: application/json' -H "Authorization: Bearer $SLACK_BOT_TOKEN" --data "$PAYLOAD" https://slack.com/api/chat.postMessage
