name: Notify on Push to UAT

on:
  push:
    branches:
      - UAT

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Commit Details
        id: get_commit_details
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "committer_name=$(git log -1 --pretty=%cn)" >> $GITHUB_ENV
          echo "commit_url=${{ github.event.head_commit.url }}" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C07GJ2TGW7N
          payload: |
            {
              "channel": "C07GJ2TGW7N",
              "text": "🚀 Se han añadido nuevos cambios a la rama UAT",
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": "Detalles del último commit:",
                  "fields": [
                    {
                      "title": "Mensaje del Commit",
                      "value": "${{ env.commit_message }}",
                      "short": false
                    },
                    {
                      "title": "Autor",
                      "value": "${{ env.committer_name }}",
                      "short": true
                    }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": "Ver Commit",
                      "url": "${{ env.commit_url }}",
                      "style": "primary"
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                  "ts": "{{ github.event.head_commit.timestamp }}"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
